from typing import TypedDict, List, Optional

class AgentState(TypedDict):
    issue_number: int
    title: str
    body: str
    category: Optional[str]         # Bug | Question | Feature Request | Other
    retrieved_docs: List[str]      # Context chunks fetched from ChromaDB
    draft_response: Optional[str]   # Cited Markdown draft generated by Gemini
    confidence_score: float         # 0.0 to 1.0 confidence rating
    status: str                     # DRAFTED | NEEDS_HUMAN_REVIEW